econ_data:
  - series_id: "CPIAUCNS"
    transforms: ['yoy_percentage_change']
  - series_id: "GS30"
    transforms: ['identity']
tickers:
  - symbol: "TMF"
    transforms: ['identity']
start_date: "2000-01-01"
end_date: "2024-12-31"